[2024-04-15T10:40:17.123+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-15T10:37:42.250164+00:00 [queued]>
[2024-04-15T10:40:17.129+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-15T10:37:42.250164+00:00 [queued]>
[2024-04-15T10:40:17.129+0000] {taskinstance.py:2171} INFO - Starting attempt 4 of 5
[2024-04-15T10:40:17.144+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_reddit_data> on 2024-04-15 10:37:42.250164+00:00
[2024-04-15T10:40:17.155+0000] {standard_task_runner.py:60} INFO - Started process 440 to run task
[2024-04-15T10:40:17.158+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'reddit_api_dag', 'get_reddit_data', 'manual__2024-04-15T10:37:42.250164+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/reddit_api_dag.py', '--cfg-path', '/tmp/tmp1dhzgzi0']
[2024-04-15T10:40:17.158+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask get_reddit_data
[2024-04-15T10:40:17.204+0000] {task_command.py:423} INFO - Running <TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-15T10:37:42.250164+00:00 [running]> on host 0f6dc4f57929
[2024-04-15T10:40:17.283+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='66130047@dpu.ac.th' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='reddit_api_dag' AIRFLOW_CTX_TASK_ID='get_reddit_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T10:37:42.250164+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-15T10:37:42.250164+00:00'
[2024-04-15T10:40:17.286+0000] {warnings.py:109} WARNING - /opt/***/dags/reddit_api_dag.py:62: AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
  pg_hook = PostgresHook(

[2024-04-15T10:40:17.293+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-15T10:40:19.731+0000] {logging_mixin.py:188} INFO - score: 1312
[2024-04-15T10:40:19.732+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_api_dag.py", line 33, in _get_reddit_data
    _save_to_database(top_posts)
  File "/opt/airflow/dags/reddit_api_dag.py", line 87, in _save_to_database
    cursor.execute(insert_query, data_tuple)
psycopg2.errors.UndefinedColumn: column "score" of relation "reddit_posts" does not exist
LINE 2: ...fullname, subreddit, selftext, url, num_comments, score, cre...
                                                             ^

[2024-04-15T10:40:19.739+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_api_dag, task_id=get_reddit_data, execution_date=20240415T103742, start_date=20240415T104017, end_date=20240415T104019
[2024-04-15T10:40:19.749+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-04-15T10:40:19.749+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-04-15T10:40:19.749+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-04-15T10:40:19.750+0000] {email.py:281} INFO - Sent an alert email to ['66130047@dpu.ac.th']
[2024-04-15T10:40:19.770+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task get_reddit_data (column "score" of relation "reddit_posts" does not exist
LINE 2: ...fullname, subreddit, selftext, url, num_comments, score, cre...
                                                             ^
; 440)
[2024-04-15T10:40:19.815+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-15T10:40:19.834+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
