[2024-04-15T16:23:04.556+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T16:23:04.564+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_visualization.generate_visualizations scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T16:23:04.565+0000] {taskinstance.py:2171} INFO - Starting attempt 7 of 8
[2024-04-15T16:23:04.580+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2024-04-14 00:00:00+00:00
[2024-04-15T16:23:04.586+0000] {standard_task_runner.py:60} INFO - Started process 2379 to run task
[2024-04-15T16:23:04.589+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_visualization', 'generate_visualizations', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dbt_visualization.py', '--cfg-path', '/tmp/tmppau9q5fy']
[2024-04-15T16:23:04.590+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask generate_visualizations
[2024-04-15T16:23:04.630+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_visualization.generate_visualizations scheduled__2024-04-14T00:00:00+00:00 [running]> on host ec3d883e7b78
[2024-04-15T16:23:04.706+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='66130047@dpu.ac.th' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_visualization' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T16:23:04.713+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-15T16:23:04.723+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dbt_visualization.py:27 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-15T16:23:04.813+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-15T16:23:04.888+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dbt_visualization.py", line 37, in _generate_visualizations
    plt.savefig(f'/trending_topics_{timestamp}.png')  # Specify the path to save the figure
  File "/home/airflow/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/home/airflow/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/airflow/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/airflow/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/home/airflow/.local/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/PIL/Image.py", line 2456, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: '/trending_topics_2024-04-14T00:00:00+00:00.png'
[2024-04-15T16:23:04.899+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_visualization, task_id=generate_visualizations, execution_date=20240414T000000, start_date=20240415T162304, end_date=20240415T162304
[2024-04-15T16:23:04.910+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-04-15T16:23:04.910+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-04-15T16:23:04.911+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-04-15T16:23:04.912+0000] {email.py:281} INFO - Sent an alert email to ['66130047@dpu.ac.th']
[2024-04-15T16:23:04.933+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 102 for task generate_visualizations ([Errno 13] Permission denied: '/trending_topics_2024-04-14T00:00:00+00:00.png'; 2379)
[2024-04-15T16:23:04.961+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-15T16:23:04.982+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
