[2024-04-16T04:56:15.757+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dbt_visualization.fetch_url manual__2024-04-16T04:56:13.162565+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
