[2024-04-14T14:57:59.908+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-14T14:22:58.929834+00:00 [queued]>
[2024-04-14T14:57:59.914+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-14T14:22:58.929834+00:00 [queued]>
[2024-04-14T14:57:59.914+0000] {taskinstance.py:2171} INFO - Starting attempt 11 of 12
[2024-04-14T14:57:59.929+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_reddit_data> on 2024-04-14 14:22:58.929834+00:00
[2024-04-14T14:57:59.938+0000] {standard_task_runner.py:60} INFO - Started process 2563 to run task
[2024-04-14T14:57:59.940+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'reddit_api_dag', 'get_reddit_data', 'manual__2024-04-14T14:22:58.929834+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/reddit_api_dag.py', '--cfg-path', '/tmp/tmp5sbx29un']
[2024-04-14T14:57:59.941+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask get_reddit_data
[2024-04-14T14:57:59.981+0000] {task_command.py:423} INFO - Running <TaskInstance: reddit_api_dag.get_reddit_data manual__2024-04-14T14:22:58.929834+00:00 [running]> on host f383f10413fd
[2024-04-14T14:58:00.049+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='66130047@dpu.ac.th' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='reddit_api_dag' AIRFLOW_CTX_TASK_ID='get_reddit_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T14:22:58.929834+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T14:22:58.929834+00:00'
[2024-04-14T14:58:00.052+0000] {warnings.py:109} WARNING - /opt/***/dags/reddit_api_dag.py:76: AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
  pg_hook = PostgresHook(postgres_conn_id="my_postgres_conn", schema="postgres")

[2024-04-14T14:58:00.063+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reddit_api_dag.py", line 46, in _get_reddit_data
    _save_to_database(top_posts)
  File "/opt/airflow/dags/reddit_api_dag.py", line 77, in _save_to_database
    connection = pg_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 128, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_postgres_conn` isn't defined
[2024-04-14T14:58:00.067+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_api_dag, task_id=get_reddit_data, execution_date=20240414T142258, start_date=20240414T145759, end_date=20240414T145800
[2024-04-14T14:58:00.081+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-04-14T14:58:00.081+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-04-14T14:58:00.081+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-04-14T14:58:00.083+0000] {email.py:281} INFO - Sent an alert email to ['66130047@dpu.ac.th']
[2024-04-14T14:58:00.100+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task get_reddit_data (The conn_id `my_postgres_conn` isn't defined; 2563)
[2024-04-14T14:58:00.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-14T14:58:00.130+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
